name = "archive-exe"
main = "src/entry.js"
compatibility_date = "2026-08-30"
keep_vars = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "archive-characters"
database_id = "acc550d1-66d7-416e-b1af-73ca22f7c230"

[secrets]
required = ["DATACAT_DEVICE_TOKEN", "DATACAT_SESSION_TOKEN"]
