-- ARCHIVE.EXE universe curation seed data
-- Data-only migration. Existing admin changes are preserved by INSERT OR IGNORE.

INSERT OR IGNORE INTO universe_curation(source_key,source_value,public_universes,parent_universe,subuniverse,active,note,updated_at) VALUES
('the vault, aka just my private bots made for me that i choose to make public.','the vault, aka just my private bots made for me that i choose to make public.','["The Vault"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('bayou crew','bayou crew','["Bayou Crew"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('bayou crew next gen','bayou crew next gen','["Bayou Crew","Bayou Crew Next Gen"]','Bayou Crew','Bayou Crew Next Gen',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('demigods; greek god alt rock band','DEMIGODS; GREEK GOD ALT ROCK BAND','["Demigods"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('hale university x vdb','hale university x vdb','["Hale University"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('arena','arena','["Arena"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('the vault but turned into mini series called hale u titans','the vault but turned into mini series called hale u titans','["The Vault"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('voodoo boys next gen','VOODOO BOYS NEXT GEN','["Voodoo Boys","Voodoo Boys Next Gen"]','Voodoo Boys','Voodoo Boys Next Gen',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('voodoo boys','VOODOO BOYS','["Voodoo Boys"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('hale university','HALE UNIVERSITY','["Hale University"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('janitorcup2025 (a leidenpotato hockey collab) - search that tag for more bots','janitorcup2025 (a leidenpotato hockey collab) - search that tag for more bots','["Collab"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('the firm','the firm','["The Firm"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('bayou crew next gen (au alt)','BAYOU CREW NEXT GEN (AU ALT)','["Bayou Crew","Bayou Crew Next Gen"]','Bayou Crew','Bayou Crew Next Gen',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('bayou crew x voodoo boys','bayou crew x voodoo boys','["Bayou Crew","Voodoo Boys"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('bridgerton inspired au','BRIDGERTON INSPIRED AU','["Bridgerton Inspired"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('bridgerton inspired collab','BRIDGERTON INSPIRED COLLAB','["Bridgerton Inspired","Collab"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('cash casino','cash casino','["Cash Casino"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('crown records rapper collab','CROWN RECORDS RAPPER COLLAB','["Collab"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('four horseman collab by leidenpotato for her 1 year server anniversary','four horseman collab by leidenpotato for her 1 year server anniversary','["Collab"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('hale reapers','HALE REAPERS','["Hale University"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('hale u','HALE U','["Hale University"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('hale university outcasts','HALE UNIVERSITY OUTCASTS','["Hale University"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('hale valkyries women''s rugby collab','HALE VALKYRIES WOMEN''S RUGBY COLLAB','["Hale University"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('hawthorne university collab by overlord melvin','hawthorne university collab by overlord melvin','["Collab"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('intergalactic by devi and sepha','INTERGALACTIC by devi and sepha','["Intergalactic"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('intergalactic by devi and sepha : a sci-fi series','INTERGALACTIC BY Devi and Sepha : a sci-fi series','["Intergalactic"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('the firm x the valentinos','THE FIRM x THE VALENTINOS','["The Firm","The Valentinos"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('the ledger collab','THE LEDGER COLLAB','["Collab"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('the vault','THE VAULT','["The Vault"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('the vault, bots made especially for me','the vault, bots made especially for me','["The Vault"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('valentinos','valentinos','["The Valentinos"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('valentinos x the firm','valentinos x the firm','["The Firm","The Valentinos"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('vault bots made for me','vault bots made for me','["The Vault"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP),
('voodoo boys x bayou crew','voodoo boys x bayou crew','["Bayou Crew","Voodoo Boys"]','','',1,'seeded from approved curation plan',CURRENT_TIMESTAMP);
