import worker from "./worker.js";

function json(data,status=200){return new Response(JSON.stringify(data,null,2),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}
function safeFilename(v,f="character"){return String(v||f).replace(/[\\/:*?"<>|]+/g,"-").replace(/\s+/g," ").trim().slice(0,100)||f}
function cardBase(card){const name=String(card?.data?.name||"Character").trim(),creator=String(card?.data?.creator||"").trim();return safeFilename(creator?`${name}_${creator}`:name,"Character")}
function attachment(name){return `attachment; filename*=UTF-8''${encodeURIComponent(name)}`}
function parseArray(v){try{const a=JSON.parse(v||"[]");return Array.isArray(a)?a:[]}catch{return[]}}
function povFromTags(tags){for(const raw of tags||[]){const key=String(raw||"").replace(/^[^\p{L}\p{N}#]+/u,"").toLowerCase().replace(/[^a-z]/g,"");if(key==="fempov"||key==="femalepov")return"FemPOV";if(key==="malepov")return"MalePOV";if(key==="anypov")return"AnyPOV"}return""}
function universeFromName(name){const parts=String(name||"").split("|").map(x=>x.trim()).filter(Boolean);return parts.length>1?parts[parts.length-1]:""}
function normalizeUniverse(row){const stored=String(row?.universe||"").trim();if(stored&&!/^janitor\s*ai$/i.test(stored)&&stored.toLowerCase()!=="janitor")return stored;return universeFromName(row?.name)||"UNCLASSIFIED"}
function normalizeDbCharacter(r,origin){const uuid=r.janitor_uuid,universe=normalizeUniverse(r),tags=parseArray(r.tags);return{id:r.slug||uuid,nameRu:"",nameEn:r.name||"Character",author:r.author||"Unknown",authorUrl:r.author_url||"",universe,pov:povFromTags(tags),tags,hashtags:parseArray(r.hashtags),short:r.short_description||"",full:r.description||"",scenario:r.scenario||"",image:r.image_url||"",platform:"JANITOR",url:r.janitor_url||`https://janitorai.com/characters/${uuid}`,download:`${origin}/api/characters/${uuid}/card`,downloadPng:`${origin}/api/characters/${uuid}/card.png`,lorebook:r.lorebook_url||"",lorebookTitle:r.lorebook_url?`${universe} LOREBOOK`:"",intros:parseArray(r.intros),isNew:false,janitorUuid:uuid,datacatUrl:r.datacat_url||"",source:r.source||"janitor",sourceLabel:"JanitorAI"}}
async function catalogCharacters(request,env){try{const url=new URL(request.url),limit=Math.min(Math.max(Number(url.searchParams.get("limit")||500),1),1000);const res=await env.DB.prepare("SELECT * FROM characters WHERE status = 'published' ORDER BY updated_at DESC LIMIT ?").bind(limit).all();const rows=Array.isArray(res?.results)?res.results:[];return json({ok:true,count:rows.length,characters:rows.map(r=>normalizeDbCharacter(r,url.origin))})}catch(e){return json({ok:false,error:"CATALOG_DB_ERROR",message:String(e?.message||e)},500)}}
async function catalogLorebooks(request,env){try{const url=new URL(request.url);const res=await env.DB.prepare("SELECT janitor_uuid,name,author,universe,lorebook_url,status FROM characters WHERE status = 'published' AND lorebook_url IS NOT NULL AND lorebook_url != '' ORDER BY author,name").all();const rows=Array.isArray(res?.results)?res.results:[];const items=rows.map(r=>{const universe=normalizeUniverse(r);return{id:`${r.janitor_uuid}:lorebook`,janitorUuid:r.janitor_uuid,characterName:r.name||"Character",author:r.author||"Unknown",universe,title:`${universe} LOREBOOK`,download:r.lorebook_url||`${url.origin}/api/characters/${r.janitor_uuid}/lorebook`,source:"janitor"}});return json({ok:true,count:items.length,lorebooks:items})}catch(e){return json({ok:false,error:"LOREBOOK_CATALOG_DB_ERROR",message:String(e?.message||e)},500)}}
function stripHtmlText(v){return String(v||"").replace(/<script[\s\S]*?<\/script>/gi,"").replace(/<style[\s\S]*?<\/style>/gi,"").replace(/<[^>]+>/g," ").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/\s+/g," ").trim()}
async function scanDatacatCreator(request){
  const reqUrl=new URL(request.url),raw=reqUrl.searchParams.get("url");
  if(!raw)return json({ok:false,error:"MISSING_CREATOR_URL"},400);
  let base;try{base=new URL(raw)}catch{return json({ok:false,error:"INVALID_CREATOR_URL"},400)}
  const creatorMatch=base.pathname.match(/^\/creators\/janitor\/([0-9a-f-]{36})\/?$/i);
  if(base.protocol!=="https:"||base.hostname!=="datacat.run"||!creatorMatch)return json({ok:false,error:"DATACAT_CREATOR_URL_REQUIRED"},400);
  const creatorId=creatorMatch[1].toLowerCase(),found=new Map();let emptyStreak=0,pagesScanned=0;
  try{
    for(let page=1;page<=50;page++){
      const target=new URL(base.toString());target.searchParams.set("page",String(page));
      const r=await fetch(target.toString(),{redirect:"follow",headers:{"accept":"text/html,application/xhtml+xml","user-agent":"ARCHIVE.EXE/1.8"}});
      if(!r.ok)return json({ok:false,error:"DATACAT_CREATOR_HTTP",status:r.status,page},502);
      let html=await r.text();pagesScanned=page;
      html=html.replace(/\\\//g,"/");
      const before=found.size;
      const linkRe=/href=["']([^"']*\/characters\/(?:recent\/janitor\/)?([0-9a-f-]{36})[^"']*)["'][^>]*>([\s\S]{0,1200}?)<\/a>/ig;
      let m;
      while((m=linkRe.exec(html))){const id=m[2].toLowerCase();if(id===creatorId)continue;const name=stripHtmlText(m[3])||id;if(!found.has(id))found.set(id,{id,name})}
      const anyRe=/\/characters\/(?:recent\/janitor\/)?([0-9a-f-]{36})/ig;
      while((m=anyRe.exec(html))){const id=m[1].toLowerCase();if(id!==creatorId&&!found.has(id))found.set(id,{id,name:id})}
      const added=found.size-before;emptyStreak=added?0:emptyStreak+1;
      const range=stripHtmlText(html).match(/(\d+)\s*[-–]\s*(\d+)\s+of\s+(\d+)/i);
      if(range&&found.size>=Number(range[3]))break;
      if(emptyStreak>=2)break;
    }
    return json({ok:true,creatorId,count:found.size,pagesScanned,characters:[...found.values()]});
  }catch(e){return json({ok:false,error:"DATACAT_CREATOR_SCAN_ERROR",message:String(e?.message||e),pagesScanned},502)}
}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function u32(n){return new Uint8Array([(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255])}
function concat(parts){let n=0;for(const p of parts)n+=p.length;const out=new Uint8Array(n);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function chunk(type,data){const t=new TextEncoder().encode(type),crc=crc32(concat([t,data]));return concat([u32(data.length),t,data,u32(crc)])}
function utf8Base64(text){const bytes=new TextEncoder().encode(text);let bin="";for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(bin)}
function isPng(b){return b.length>8&&b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71&&b[4]===13&&b[5]===10&&b[6]===26&&b[7]===10}
function embedCard(png,card){if(!isPng(png))throw new Error("SOURCE_NOT_PNG");const parts=[png.slice(0,8)],payload=new TextEncoder().encode(`chara\0${utf8Base64(JSON.stringify(card))}`);let o=8,inserted=false;while(o+12<=png.length){const len=((png[o]<<24)|(png[o+1]<<16)|(png[o+2]<<8)|png[o+3])>>>0,end=o+12+len;if(end>png.length)throw new Error("INVALID_PNG");const type=String.fromCharCode(...png.slice(o+4,o+8));if(type==="IEND"&&!inserted){parts.push(chunk("tEXt",payload));inserted=true}if(!(type==="tEXt"&&new TextDecoder().decode(png.slice(o+8,o+8+Math.min(len,5)))==="chara"))parts.push(png.slice(o,end));o=end}if(!inserted)throw new Error("PNG_IEND_MISSING");return concat(parts)}
async function getCard(request,env,ctx,uuid){const u=new URL(request.url);u.pathname=`/api/characters/${uuid}/card`;u.search="";const r=await worker.fetch(new Request(u.toString(),{method:"GET",headers:request.headers}),env,ctx);const text=await r.text();if(!r.ok)return{response:new Response(text,{status:r.status,headers:r.headers})};try{return{card:JSON.parse(text)}}catch{return{response:json({ok:false,error:"INVALID_CARD_JSON"},502)}}}
async function fetchJannyPng(uuid){try{const r=await fetch("https://api.jannyai.com/api/v1/download",{method:"POST",headers:{"content-type":"application/json","accept":"application/json","user-agent":"ARCHIVE.EXE/1.7"},body:JSON.stringify({characterId:uuid}),redirect:"follow"});if(!r.ok)return{ok:false,state:`JANNY_HTTP_${r.status}`};const data=await r.json(),downloadUrl=data?.downloadUrl||data?.download_url;if(!downloadUrl)return{ok:false,state:"JANNY_NO_DOWNLOAD_URL"};const f=await fetch(downloadUrl,{redirect:"follow"});if(!f.ok)return{ok:false,state:`JANNY_FILE_HTTP_${f.status}`};const bytes=new Uint8Array(await f.arrayBuffer());return isPng(bytes)?{ok:true,bytes}:{ok:false,state:"JANNY_FILE_NOT_PNG"}}catch(e){return{ok:false,state:"JANNY_FETCH_ERROR",detail:String(e?.message||e)}}}
async function imageProxy(request){const url=new URL(request.url),raw=url.searchParams.get("url");if(!raw)return json({ok:false,error:"MISSING_URL"},400);let target;try{target=new URL(raw)}catch{return json({ok:false,error:"INVALID_URL"},400)}if(target.protocol!=="https:"||![/^(?:media\.)?datacat\.run$/i,/\.datacat\.run$/i].some(r=>r.test(target.hostname)))return json({ok:false,error:"HOST_NOT_ALLOWED"},403);try{const upstream=await fetch(target.toString(),{redirect:"follow",headers:{"accept":"image/avif,image/webp,image/apng,image/*,*/*;q=0.8","user-agent":"ARCHIVE.EXE/1.7"}});if(!upstream.ok)return json({ok:false,error:"UPSTREAM_IMAGE_ERROR",status:upstream.status},502);const h=new Headers();h.set("content-type",upstream.headers.get("content-type")||"application/octet-stream");h.set("cache-control","public, max-age=3600");h.set("access-control-allow-origin","*");h.set("cross-origin-resource-policy","cross-origin");return new Response(upstream.body,{status:200,headers:h})}catch(e){return json({ok:false,error:"IMAGE_PROXY_ERROR",message:String(e?.message||e)},502)}}
function canvasPngDataUrl(avatar,card){const safeAvatar=JSON.stringify(String(avatar||"")),safeCard=JSON.stringify(card);return `<!doctype html><meta charset="utf-8"><title>PNG Card Builder</title><style>body{background:#0b0e0b;color:#d8deca;font:14px monospace;padding:24px}canvas{max-width:320px;display:block;margin-bottom:16px}button{padding:12px 18px}</style><canvas id="c"></canvas><button id="b" disabled>DOWNLOAD PNG CARD</button><p id="s">Preparing image…</p><script>const avatar=${safeAvatar},card=${safeCard};const enc=new TextEncoder();function crc32(a){let c=0xffffffff;for(const b of a){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}function u32(n){return new Uint8Array([(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255])}function cat(ps){let n=ps.reduce((a,p)=>a+p.length,0),o=new Uint8Array(n),i=0;for(const p of ps){o.set(p,i);i+=p.length}return o}function ch(t,d){let x=enc.encode(t);return cat([u32(d.length),x,d,u32(crc32(cat([x,d])))])}function b64(s){let a=enc.encode(s),x='';for(let i=0;i<a.length;i+=32768)x+=String.fromCharCode(...a.subarray(i,i+32768));return btoa(x)}function embed(a){let p=new Uint8Array(a),parts=[p.slice(0,8)],o=8,done=false,data=enc.encode('chara\\0'+b64(JSON.stringify(card)));while(o+12<=p.length){let l=((p[o]<<24)|(p[o+1]<<16)|(p[o+2]<<8)|p[o+3])>>>0,e=o+12+l,t=String.fromCharCode(...p.slice(o+4,o+8));if(t==='IEND'&&!done){parts.push(ch('tEXt',data));done=true}parts.push(p.slice(o,e));o=e}return cat(parts)}const img=new Image();img.crossOrigin='anonymous';img.onload=()=>{c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d').drawImage(img,0,0);s.textContent='Ready.';b.disabled=false;b.onclick=()=>c.toBlob(async blob=>{let bytes=embed(await blob.arrayBuffer()),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([bytes],{type:'image/png'}));a.download=${JSON.stringify(cardBase(card)+'.png')};a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png')};img.onerror=()=>s.textContent='Could not load proxied image.';img.src=avatar;<\/script>`}
async function pngDownload(request,env,ctx,uuid){const got=await getCard(request,env,ctx,uuid);if(got.response)return got.response;let source=await fetchJannyPng(uuid);if(source.ok){try{const png=embedCard(source.bytes,got.card);return new Response(png,{headers:{"content-type":"image/png","content-disposition":attachment(`${cardBase(got.card)}.png`),"cache-control":"private, no-store"}})}catch{}}
const avatar=got.card?.data?.extensions?.archive_exe?.avatar_url||"";if(!avatar)return json({ok:false,state:"PNG_SOURCE_NOT_AVAILABLE",janitorUuid:uuid,detail:source.state},502);const origin=new URL(request.url).origin,proxied=`${origin}/api/image-proxy?url=${encodeURIComponent(avatar)}`;return new Response(canvasPngDataUrl(proxied,got.card),{status:200,headers:{"content-type":"text/html; charset=utf-8","cache-control":"private, no-store"}})}
async function jsonDownload(request,env,ctx,uuid){const got=await getCard(request,env,ctx,uuid);if(got.response)return got.response;return new Response(JSON.stringify(got.card,null,2),{headers:{"content-type":"application/json; charset=utf-8","content-disposition":attachment(`${cardBase(got.card)}.json`),"cache-control":"private, no-store"}})}
export default{async fetch(request,env,ctx){const url=new URL(request.url);if(request.method==="GET"){if(url.pathname==="/api/characters")return catalogCharacters(request,env);if(url.pathname==="/api/lorebooks")return catalogLorebooks(request,env);if(url.pathname==="/api/admin/creator-scan")return scanDatacatCreator(request);if(url.pathname==="/api/image-proxy")return imageProxy(request);let m=url.pathname.match(/^\/api\/characters\/([0-9a-f-]{36})\/card\.png$/i);if(m)return pngDownload(request,env,ctx,m[1].toLowerCase());m=url.pathname.match(/^\/api\/characters\/([0-9a-f-]{36})\/card$/i);if(m)return jsonDownload(request,env,ctx,m[1].toLowerCase());if(url.pathname==="/api/debug/retrieval")return json({ok:false,state:"DEBUG_REEXTRACT_DISABLED"},410)}return worker.fetch(request,env,ctx)}};
