import worker from './worker.js';

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function safeFilename(v,f='character'){return String(v||f).replace(/[\\/:*?"<>|]+/g,'-').replace(/\s+/g,' ').trim().slice(0,100)||f}
function cardBase(card){const name=String(card?.data?.name||'Character').trim(),creator=String(card?.data?.creator||'').trim();return safeFilename(creator?`${name}_${creator}`:name,'Character')}
function attachment(name){return `attachment; filename*=UTF-8''${encodeURIComponent(name)}`}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function u32(n){return new Uint8Array([(n>>>24)&255,(n>>>16)&255,(n>>>8)&255,n&255])}
function concat(parts){let n=0;for(const p of parts)n+=p.length;const out=new Uint8Array(n);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function chunk(type,data){const t=new TextEncoder().encode(type),crc=crc32(concat([t,data]));return concat([u32(data.length),t,data,u32(crc)])}
function utf8Base64(text){const bytes=new TextEncoder().encode(text);let bin='';for(let i=0;i<bytes.length;i+=0x8000)bin+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(bin)}
function isPng(b){return b.length>8&&b[0]===137&&b[1]===80&&b[2]===78&&b[3]===71&&b[4]===13&&b[5]===10&&b[6]===26&&b[7]===10}
function embedCard(png,card){if(!isPng(png))throw new Error('SOURCE_NOT_PNG');const parts=[png.slice(0,8)],payload=new TextEncoder().encode(`chara\0${utf8Base64(JSON.stringify(card))}`);let o=8,inserted=false;while(o+12<=png.length){const len=((png[o]<<24)|(png[o+1]<<16)|(png[o+2]<<8)|png[o+3])>>>0,end=o+12+len;if(end>png.length)throw new Error('INVALID_PNG');const type=String.fromCharCode(...png.slice(o+4,o+8));if(type==='IEND'&&!inserted){parts.push(chunk('tEXt',payload));inserted=true}if(!(type==='tEXt'&&new TextDecoder().decode(png.slice(o+8,o+8+Math.min(len,5)))==='chara'))parts.push(png.slice(o,end));o=end}if(!inserted)throw new Error('PNG_IEND_MISSING');return concat(parts)}
async function getCard(request,env,ctx,uuid){const u=new URL(request.url);u.pathname=`/api/characters/${uuid}/card`;u.search='';const r=await worker.fetch(new Request(u.toString(),{method:'GET',headers:request.headers}),env,ctx);const text=await r.text();if(r.status!==200)return{response:new Response(text,{status:r.status,headers:r.headers})};try{return{card:JSON.parse(text)}}catch{return{response:json({ok:false,error:'INVALID_CARD_JSON'},502)}}}
async function fetchJannyPng(uuid){try{const r=await fetch('https://api.jannyai.com/api/v1/download',{method:'POST',headers:{'content-type':'application/json','accept':'application/json','user-agent':'ARCHIVE.EXE/1.7'},body:JSON.stringify({characterId:uuid}),redirect:'follow'});if(!r.ok)return{ok:false,state:`JANNY_HTTP_${r.status}`};const data=await r.json(),downloadUrl=data?.downloadUrl||data?.download_url;if(!downloadUrl)return{ok:false,state:'JANNY_NO_DOWNLOAD_URL'};const f=await fetch(downloadUrl,{redirect:'follow'});if(!f.ok)return{ok:false,state:`JANNY_FILE_HTTP_${f.status}`};const bytes=new Uint8Array(await f.arrayBuffer());return isPng(bytes)?{ok:true,bytes}:{ok:false,state:'JANNY_FILE_NOT_PNG'}}catch(e){return{ok:false,state:'JANNY_FETCH_ERROR',detail:String(e?.message||e)}}}
function allowedImageTarget(raw){let target;try{target=new URL(String(raw||''))}catch{return{ok:false,error:'INVALID_URL'}}if(target.protocol!=='https:'||![/^(?:media\.)?datacat\.run$/i,/\.datacat\.run$/i].some(r=>r.test(target.hostname)))return{ok:false,error:'HOST_NOT_ALLOWED'};return{ok:true,target}}
export async function fetchAvatarPng(url,images){const allowed=allowedImageTarget(url);if(!allowed.ok)return{ok:false,state:`AVATAR_${allowed.error}`};let bindingFailure='';if(images?.input){try{const source=await fetch(allowed.target.toString(),{redirect:'follow',headers:{accept:'image/*','user-agent':'ARCHIVE.EXE/1.9'}});if(!source.ok)return{ok:false,state:`AVATAR_HTTP_${source.status}`};if(!source.body)return{ok:false,state:'AVATAR_EMPTY_BODY'};const output=await images.input(source.body).transform({fit:'scale-down',width:1600,height:2400}).output({format:'image/png',anim:false}),response=output.response();if(!response.ok)bindingFailure=`AVATAR_IMAGES_HTTP_${response.status}`;else{const bytes=new Uint8Array(await response.arrayBuffer());if(isPng(bytes))return{ok:true,bytes};bindingFailure='AVATAR_IMAGES_NOT_PNG'}}catch(e){bindingFailure='AVATAR_IMAGES_ERROR'}}try{const r=await fetch(allowed.target.toString(),{redirect:'follow',cf:{image:{format:'png',fit:'scale-down',width:1600,height:2400}},headers:{accept:'image/png,image/*;q=.8','user-agent':'ARCHIVE.EXE/1.9'}});if(!r.ok)return{ok:false,state:`AVATAR_HTTP_${r.status}`};const bytes=new Uint8Array(await r.arrayBuffer());return isPng(bytes)?{ok:true,bytes}:{ok:false,state:bindingFailure||'AVATAR_NOT_PNG'}}catch(e){return{ok:false,state:bindingFailure||'AVATAR_FETCH_ERROR',detail:String(e?.message||e)}}}
async function imageProxy(request){const url=new URL(request.url),raw=url.searchParams.get('url');if(!raw)return json({ok:false,error:'MISSING_URL'},400);const allowed=allowedImageTarget(raw);if(!allowed.ok)return json({ok:false,error:allowed.error},allowed.error==='INVALID_URL'?400:403);try{const upstream=await fetch(allowed.target.toString(),{redirect:'follow',headers:{accept:'image/avif,image/webp,image/apng,image/*,*/*;q=0.8','user-agent':'ARCHIVE.EXE/1.7'}});if(!upstream.ok)return json({ok:false,error:'UPSTREAM_IMAGE_ERROR',status:upstream.status},502);const h=new Headers();h.set('content-type',upstream.headers.get('content-type')||'application/octet-stream');h.set('cache-control','public, max-age=3600');h.set('access-control-allow-origin','*');h.set('cross-origin-resource-policy','cross-origin');return new Response(upstream.body,{status:200,headers:h})}catch(e){return json({ok:false,error:'IMAGE_PROXY_ERROR',message:String(e?.message||e)},502)}}
async function pngDownload(request,env,ctx,uuid){const got=await getCard(request,env,ctx,uuid);if(got.response)return got.response;const janny=await fetchJannyPng(uuid);if(janny.ok){try{return new Response(embedCard(janny.bytes,got.card),{headers:{'content-type':'image/png','content-disposition':attachment(`${cardBase(got.card)}.png`),'cache-control':'private, no-store'}})}catch{}}const avatar=got.card?.data?.extensions?.archive_exe?.avatar_url||'';if(!avatar)return json({ok:false,state:'PNG_SOURCE_NOT_AVAILABLE',janitorUuid:uuid,detail:{janny:janny.state||'UNKNOWN',avatar:'MISSING'}},502);const avatarSource=await fetchAvatarPng(avatar,env.IMAGES);if(avatarSource.ok){try{return new Response(embedCard(avatarSource.bytes,got.card),{headers:{'content-type':'image/png','content-disposition':attachment(`${cardBase(got.card)}.png`),'cache-control':'private, no-store'}})}catch{}}return json({ok:false,state:'PNG_SOURCE_NOT_AVAILABLE',janitorUuid:uuid,detail:{janny:janny.state||'UNKNOWN',avatar:avatarSource.state||'UNKNOWN'}},502)}
async function jsonDownload(request,env,ctx,uuid){const got=await getCard(request,env,ctx,uuid);if(got.response)return got.response;return new Response(JSON.stringify(got.card,null,2),{headers:{'content-type':'application/json; charset=utf-8','content-disposition':attachment(`${cardBase(got.card)}.json`),'cache-control':'private, no-store'}})}

export async function handleEntryRoute(request,env,ctx){const url=new URL(request.url);if(request.method==='GET'){if(url.pathname==='/api/image-proxy')return imageProxy(request);let m=url.pathname.match(/^\/api\/characters\/([0-9a-f-]{36})\/card\.png$/i);if(m)return pngDownload(request,env,ctx,m[1].toLowerCase());m=url.pathname.match(/^\/api\/characters\/([0-9a-f-]{36})\/card$/i);if(m)return jsonDownload(request,env,ctx,m[1].toLowerCase());if(url.pathname==='/api/debug/retrieval')return json({ok:false,state:'DEBUG_REEXTRACT_DISABLED'},410)}return null}
