import app from './main.js';

function json(data,status=200,headers={}){return new Response(JSON.stringify(data,null,2),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...headers}})}
function arr(v){try{const x=JSON.parse(v||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function clean(v){return typeof v==='string'?v.trim():''}
function safeFilename(v,f='lorebook'){return String(v||f).replace(/[\\/:*?"<>|]+/g,'-').replace(/\s+/g,' ').trim().slice(0,120)||f}
function sourceUniverse(c){const fields=['universe','universe_name','universeName','series','series_name','seriesName','franchise','franchise_name','franchiseName','world','world_name','worldName'];for(const field of fields){const value=clean(c?.[field]);if(value)return{value,field}}return{value:'',field:''}}
function lorebooksFrom(c){return(Array.isArray(c?.scripts)?c.scripts:[]).filter(s=>s&&String(s.type||'').toLowerCase()==='lorebook'&&s.is_public!==false&&s.is_code_public!==false&&typeof s.script==='string'&&s.script.trim()).map((s,index)=>({index,title:clean(s.title),script:s.script.trim()}))}
function dcHeaders(env){return{'accept':'application/json','x-device-token':env.DATACAT_DEVICE_TOKEN||'','x-session-token':env.DATACAT_SESSION_TOKEN||'','user-agent':'ARCHIVE.EXE/source-truth-2.0'}}
async function dcModal(env,uuid){const r=await fetch(`https://datacat.run/api/characters/recent-public/${encodeURIComponent(uuid)}?view=modal&sourceKind=janitor`,{headers:dcHeaders(env),redirect:'follow'});const text=await r.text();let data=null;try{data=JSON.parse(text)}catch{}if(!r.ok)return{ok:false,status:r.status,error:text.slice(0,300)};const c=data?.character;return c&&typeof c==='object'?{ok:true,c}:{ok:false,status:502,error:'NO_CHARACTER_OBJECT'}}
async function sha256Hex(text){const bytes=new TextEncoder().encode(text),hash=new Uint8Array(await crypto.subtle.digest('SHA-256',bytes));return[...hash].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function ensureSchema(env){for(const sql of['ALTER TABLE characters ADD COLUMN lorebook_title TEXT','ALTER TABLE characters ADD COLUMN universe_source_field TEXT',`CREATE TABLE IF NOT EXISTS lorebooks (id TEXT PRIMARY KEY,title TEXT NOT NULL DEFAULT '',script TEXT NOT NULL,author TEXT DEFAULT '',source TEXT DEFAULT 'datacat',created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP)`,`CREATE TABLE IF NOT EXISTS character_lorebooks (character_uuid TEXT NOT NULL,lorebook_id TEXT NOT NULL,ordinal INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(character_uuid,lorebook_id))`,'CREATE INDEX IF NOT EXISTS idx_character_lorebooks_character ON character_lorebooks(character_uuid)','CREATE INDEX IF NOT EXISTS idx_character_lorebooks_lorebook ON character_lorebooks(lorebook_id)']){try{await env.DB.prepare(sql).run()}catch(e){if(!/duplicate column|already exists/i.test(String(e?.message||e)))throw e}}}
async function syncLorebooks(env,c,uuid){await ensureSchema(env);const books=lorebooksFrom(c),author=clean(c?.creator_name||c?.creatorName);await env.DB.prepare('DELETE FROM character_lorebooks WHERE character_uuid=?').bind(uuid).run();const saved=[];for(const b of books){const id=(await sha256Hex(b.script)).slice(0,32);await env.DB.prepare(`INSERT INTO lorebooks(id,title,script,author,source,updated_at) VALUES(?,?,?,?, 'datacat', CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET title=excluded.title,script=excluded.script,author=excluded.author,updated_at=CURRENT_TIMESTAMP`).bind(id,b.title,b.script,author).run();await env.DB.prepare('INSERT OR REPLACE INTO character_lorebooks(character_uuid,lorebook_id,ordinal) VALUES(?,?,?)').bind(uuid,id,b.index).run();saved.push({id,title:b.title,ordinal:b.index})}return saved}
function canonicalAuthors(rows){const groups=new Map();for(const r of rows){const v=clean(r.author);if(!v)continue;const k=v.toLocaleLowerCase();if(!groups.has(k))groups.set(k,new Map());groups.get(k).set(v,(groups.get(k).get(v)||0)+1)}const out=new Map();for(const[k,variants]of groups){const winner=[...variants.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0]?.[0]||'';out.set(k,winner)}return out}
function canonAuthor(v,map){const raw=clean(v);return raw?(map.get(raw.toLocaleLowerCase())||raw):'Unknown'}
function normalizeRow(r,origin,authors){const uuid=r.janitor_uuid,universe=clean(r.universe)||'UNCLASSIFIED',author=canonAuthor(r.author,authors),loreCount=Number(r.lorebook_count||0);return{id:r.slug||uuid,nameRu:'',nameEn:r.name||'Character',author,authorUrl:r.author_url||'',universe,pov:r.pov||'AnyPOV',tags:arr(r.tags),hashtags:arr(r.hashtags),short:r.short_description||'',full:r.description||'',scenario:r.scenario||'',image:r.image_url||'',platform:'JANITOR',url:r.janitor_url||`https://janitorai.com/characters/${uuid}`,download:`${origin}/api/characters/${uuid}/card`,downloadPng:`${origin}/api/characters/${uuid}/card.png`,lorebook:loreCount?`${origin}/api/characters/${uuid}/lorebooks`:'',lorebookCount:loreCount,intros:arr(r.intros),isNew:false,janitorUuid:uuid,datacatUrl:r.datacat_url||'',source:r.source||'janitor',sourceLabel:'JanitorAI',universeSourceField:r.universe_source_field||''}}
async function characters(request,env){await ensureSchema(env);const u=new URL(request.url),limit=Math.min(Math.max(Number(u.searchParams.get('limit')||500),1),1000),res=await env.DB.prepare(`SELECT c.*,(SELECT COUNT(*) FROM character_lorebooks cl WHERE cl.character_uuid=c.janitor_uuid) AS lorebook_count FROM characters c WHERE c.status='published' ORDER BY c.updated_at DESC LIMIT ?`).bind(limit).all(),rows=Array.isArray(res?.results)?res.results:[],authors=canonicalAuthors(rows);return json({ok:true,count:rows.length,characters:rows.map(r=>normalizeRow(r,u.origin,authors)),namingPolicy:'source-truth',lorebookModel:'many-to-many'})}
async function characterLorebooks(request,env,uuid){await ensureSchema(env);const u=new URL(request.url),res=await env.DB.prepare(`SELECT l.id,l.title,l.author,cl.ordinal FROM character_lorebooks cl JOIN lorebooks l ON l.id=cl.lorebook_id WHERE cl.character_uuid=? ORDER BY cl.ordinal,l.title`).bind(uuid).all();const books=(res?.results||[]).map(x=>({id:x.id,title:x.title||'',author:x.author||'',ordinal:Number(x.ordinal||0),download:`${u.origin}/api/characters/${uuid}/lorebooks/${x.id}`}));return json({ok:true,janitorUuid:uuid,count:books.length,lorebooks:books})}
async function lorebookDownload(request,env,uuid,id){await ensureSchema(env);const row=await env.DB.prepare(`SELECT l.id,l.title,l.script FROM character_lorebooks cl JOIN lorebooks l ON l.id=cl.lorebook_id WHERE cl.character_uuid=? AND l.id=? LIMIT 1`).bind(uuid,id).first();if(!row)return json({ok:false,error:'LOREBOOK_NOT_LINKED_TO_CHARACTER'},404);let parsed;try{parsed=JSON.parse(row.script)}catch{parsed=row.script}return new Response(JSON.stringify(parsed,null,2),{headers:{'content-type':'application/json; charset=utf-8','content-disposition':`attachment; filename*=UTF-8''${encodeURIComponent(`${safeFilename(row.title||'Lorebook')}.json`)}`,'cache-control':'private, no-store'}})}
async function lorebooks(request,env){await ensureSchema(env);const u=new URL(request.url),res=await env.DB.prepare(`SELECT l.id,l.title,l.author,cl.character_uuid,c.name AS character_name,c.universe FROM lorebooks l JOIN character_lorebooks cl ON cl.lorebook_id=l.id JOIN characters c ON c.janitor_uuid=cl.character_uuid WHERE c.status='published' ORDER BY l.author,l.title,c.name`).all(),rows=Array.isArray(res?.results)?res.results:[],map=new Map();for(const r of rows){let x=map.get(r.id);if(!x){x={id:r.id,title:r.title||'',author:r.author||'',characterUuids:[],characterNames:[],universes:[],download:`${u.origin}/api/lorebooks/${r.id}`};map.set(r.id,x)}x.characterUuids.push(r.character_uuid);x.characterNames.push(r.character_name||'Character');const un=clean(r.universe)||'UNCLASSIFIED';if(!x.universes.includes(un))x.universes.push(un)}return json({ok:true,count:map.size,lorebooks:[...map.values()],namingPolicy:'source-truth',dedupe:'script-sha256'})}
async function globalLorebookDownload(request,env,id){await ensureSchema(env);const row=await env.DB.prepare('SELECT title,script FROM lorebooks WHERE id=? LIMIT 1').bind(id).first();if(!row)return json({ok:false,error:'LOREBOOK_NOT_FOUND'},404);let parsed;try{parsed=JSON.parse(row.script)}catch{parsed=row.script}return new Response(JSON.stringify(parsed,null,2),{headers:{'content-type':'application/json; charset=utf-8','content-disposition':`attachment; filename*=UTF-8''${encodeURIComponent(`${safeFilename(row.title||'Lorebook')}.json`)}`,'cache-control':'private, no-store'}})}
async function refreshOne(env,uuid){await ensureSchema(env);const row=await env.DB.prepare('SELECT id,name,author FROM characters WHERE janitor_uuid=? LIMIT 1').bind(uuid).first();if(!row)return{ok:false,error:'DB_RECORD_NOT_FOUND'};const dc=await dcModal(env,uuid);if(!dc.ok)return dc;const c=dc.c,uni=sourceUniverse(c),books=await syncLorebooks(env,c,uuid),name=clean(c.name||c.chat_name||c.chatName),author=clean(c.creator_name||c.creatorName);await env.DB.prepare(`UPDATE characters SET name=?,author=?,universe=?,universe_source_field=?,lorebook_title=?,lorebook_url=?,updated_at=CURRENT_TIMESTAMP WHERE janitor_uuid=?`).bind(name||row.name,author||row.author,uni.value,uni.field,books[0]?.title||'',books.length?`/api/characters/${uuid}/lorebooks`:'',uuid).run();return{ok:true,uuid,name:name||row.name,author:author||row.author,universe:uni.value||null,universeSourceField:uni.field||null,lorebookCount:books.length,lorebookTitles:books.map(b=>b.title)}}
async function reindex(request,env){await ensureSchema(env);const u=new URL(request.url),after=Math.max(0,Number(u.searchParams.get('after')||0)),limit=Math.min(Math.max(Number(u.searchParams.get('limit')||8),1),12),res=await env.DB.prepare('SELECT id,janitor_uuid FROM characters WHERE id>? ORDER BY id LIMIT ?').bind(after,limit).all(),rows=Array.isArray(res?.results)?res.results:[],results=[];for(const row of rows){const r=await refreshOne(env,row.janitor_uuid);results.push({id:row.id,...r})}const next=rows.length?rows[rows.length-1].id:after,totalRow=await env.DB.prepare('SELECT COUNT(*) AS n FROM characters').first(),remaining=await env.DB.prepare('SELECT COUNT(*) AS n FROM characters WHERE id>?').bind(next).first();return json({ok:true,processed:rows.length,after,next,total:Number(totalRow?.n||0),remaining:Number(remaining?.n||0),done:rows.length===0||Number(remaining?.n||0)===0,results})}
async function passWithRefresh(request,env,ctx){const response=await app.fetch(request,env,ctx),u=new URL(request.url);if((u.pathname==='/api/import'||u.pathname==='/api/import/status')&&response.headers.get('content-type')?.includes('application/json')){try{const d=await response.clone().json(),uuid=clean(d?.janitorUuid||d?.janitor_uuid);if(uuid&&response.ok&&response.status!==202)ctx?.waitUntil?.(refreshOne(env,uuid).catch(()=>{}))}catch{}}return response}
export default{async fetch(request,env,ctx){const u=new URL(request.url);if(request.method==='GET'&&u.pathname==='/api/characters')return characters(request,env);if(request.method==='GET'&&u.pathname==='/api/lorebooks')return lorebooks(request,env);let m=u.pathname.match(/^\/api\/characters\/([0-9a-f-]{36})\/lorebooks$/i);if(request.method==='GET'&&m)return characterLorebooks(request,env,m[1].toLowerCase());m=u.pathname.match(/^\/api\/characters\/([0-9a-f-]{36})\/lorebooks\/([0-9a-f]{32})$/i);if(request.method==='GET'&&m)return lorebookDownload(request,env,m[1].toLowerCase(),m[2].toLowerCase());m=u.pathname.match(/^\/api\/lorebooks\/([0-9a-f]{32})$/i);if(request.method==='GET'&&m)return globalLorebookDownload(request,env,m[1].toLowerCase());if(request.method==='GET'&&u.pathname==='/api/admin/reindex-source-truth')return reindex(request,env);return passWithRefresh(request,env,ctx)}};
